# Generated by Django 5.2.8 on 2025-11-29 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del departamento (ej: Recursos Humanos, IT, Ventas)', max_length=100, unique=True, verbose_name='Nombre del Departamento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del departamento y sus funciones', null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Número de cédula de identidad del empleado', max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('telefono', models.CharField(help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('telefono_emergencia', models.CharField(blank=True, help_text='Contacto de emergencia', max_length=20, null=True, verbose_name='Teléfono de Emergencia')),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento del empleado', verbose_name='Fecha de Nacimiento')),
                ('direccion', models.TextField(blank=True, help_text='Dirección de residencia', null=True, verbose_name='Dirección')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo de Sangre')),
                ('fecha_ingreso', models.DateField(help_text='Fecha en que el empleado inicia labores', verbose_name='Fecha de Ingreso')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, help_text='Salario mensual del empleado', max_digits=10, null=True, verbose_name='Salario')),
                ('estado', models.CharField(choices=[('pre_ingreso', 'Pre-ingreso'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pre_ingreso', help_text='Estado actual del proceso de onboarding', max_length=20, verbose_name='Estado')),
                ('progreso', models.IntegerField(default=0, help_text='Porcentaje de avance en el proceso de onboarding', verbose_name='Progreso (%)')),
                ('notas', models.TextField(blank=True, help_text='Notas internas de RRHH sobre el empleado', null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Supervisor directo del empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('usuario', models.OneToOneField(help_text='Usuario de Django asociado al empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-fecha_creacion'],
                'permissions': [('view_dashboard', 'Puede ver el dashboard de RRHH'), ('approve_documents', 'Puede aprobar documentos'), ('manage_onboarding', 'Puede gestionar el proceso de onboarding')],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato de Trabajo'), ('cedula', 'Cédula de Identidad'), ('nda', 'Acuerdo de Confidencialidad (NDA)'), ('titulo', 'Título Académico'), ('certificado_medico', 'Certificado Médico'), ('carta_recomendacion', 'Carta de Recomendación'), ('foto', 'Fotografía'), ('antecedentes', 'Certificado de Antecedentes'), ('otro', 'Otro')], help_text='Tipo de documento que se está subiendo', max_length=30, verbose_name='Tipo de Documento')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del documento', max_length=200, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(help_text='Archivo del documento (PDF, Word, Imagen, etc.)', upload_to='documentos/%Y/%m/', verbose_name='Archivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', help_text='Estado de verificación del documento', max_length=20, verbose_name='Estado')),
                ('obligatorio', models.BooleanField(default=False, help_text='Indica si el documento es obligatorio para completar el onboarding', verbose_name='Obligatorio')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios sobre el documento (razón de rechazo, observaciones, etc.)', null=True, verbose_name='Comentarios')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('revisado_por', models.ForeignKey(blank=True, help_text='Usuario de RRHH que revisó el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('empleado', models.ForeignKey(help_text='Empleado al que pertenece el documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestor.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre del puesto (ej: Desarrollador Backend, Contador)', max_length=150, verbose_name='Título del Puesto')),
                ('nivel', models.CharField(choices=[('junior', 'Junior'), ('semi_senior', 'Semi Senior'), ('senior', 'Senior'), ('manager', 'Manager'), ('director', 'Director'), ('ejecutivo', 'Ejecutivo')], default='junior', help_text='Nivel jerárquico del puesto', max_length=20, verbose_name='Nivel')),
                ('descripcion', models.TextField(blank=True, help_text='Responsabilidades y requisitos del puesto', null=True, verbose_name='Descripción')),
                ('salario_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Rango salarial mínimo para este puesto', max_digits=10, null=True, verbose_name='Salario Mínimo')),
                ('salario_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Rango salarial máximo para este puesto', max_digits=10, null=True, verbose_name='Salario Máximo')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el puesto está actualmente disponible', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('departamento', models.ForeignKey(help_text='Departamento al que pertenece este puesto', on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='gestor.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'ordering': ['departamento', 'titulo'],
                'unique_together': {('titulo', 'departamento')},
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(help_text='Puesto que ocupará el empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='gestor.puesto', verbose_name='Puesto'),
        ),
        migrations.CreateModel(
            name='TareaOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título breve de la tarea', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(help_text='Descripción detallada de lo que debe realizarse', verbose_name='Descripción')),
                ('responsable', models.CharField(choices=[('rrhh', 'Recursos Humanos'), ('it', 'Tecnología (IT)'), ('supervisor', 'Jefe Directo'), ('finanzas', 'Finanzas'), ('empleado', 'Empleado'), ('legal', 'Legal'), ('otro', 'Otro')], help_text='Departamento o persona responsable de completar la tarea', max_length=20, verbose_name='Responsable')),
                ('fecha_limite', models.DateField(help_text='Fecha en que debe completarse la tarea', verbose_name='Fecha Límite')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha en que se comenzó a trabajar en la tarea', null=True, verbose_name='Fecha de Inicio')),
                ('fecha_completado', models.DateField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('bloqueado', 'Bloqueado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('es_automatica', models.BooleanField(default=True, help_text='Indica si la tarea fue creada automáticamente por el sistema', verbose_name='Tarea Automática')),
                ('orden', models.IntegerField(default=0, help_text='Orden de ejecución de la tarea', verbose_name='Orden')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la tarea', null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_completadas', to=settings.AUTH_USER_MODEL, verbose_name='Completado Por')),
                ('empleado', models.ForeignKey(help_text='Empleado al que pertenece esta tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestor.empleado', verbose_name='Empleado')),
                ('responsable_usuario', models.ForeignKey(blank=True, help_text='Usuario específico asignado a la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Tarea de Onboarding',
                'verbose_name_plural': 'Tareas de Onboarding',
                'ordering': ['orden', 'fecha_limite', '-prioridad'],
            },
        ),
    ]
